version: "3.9"

services:
  jupyter:
    image: jupyter/minimal-notebook:latest
    tty: true               # false for `entrypoint` in Dockerfile
    stdin_open: true        # false for `entrypoint` in Dockerfile
    env_file:
      - ./.env
    volumes:
      - .:/home/jovyan/work
    ports:
      - 8888:${PORT:-8888}
    build:
      context: ./
      dockerfile: ./Dockerfile

networks:
  default:
    driver: bridge
